import type { SdkworkMallPcRouteContribution } from "@sdkwork/mall-pc-core";

export const sdkworkMallPcOrderRoutes = [
  {
    auth: "required",
    capability: "order",
    domain: "commerce",
    id: "buyer.mall.orders",
    packageName: "@sdkwork/mall-pc-order",
    path: "/buyer/orders",
    screen: "dashboard",
    surface: "buyer",
    title: "我的订单",
    titleKey: "order.routes.dashboard.title",
  },
  {
    auth: "required",
    capability: "order",
    domain: "commerce",
    id: "buyer.mall.orders.detail",
    packageName: "@sdkwork/mall-pc-order",
    path: "/buyer/orders/:orderId",
    screen: "order-detail",
    surface: "buyer",
    title: "订单详情",
    titleKey: "order.routes.detail.title",
  },
  {
    auth: "required",
    capability: "order",
    domain: "commerce",
    id: "buyer.mall.orders.logistics",
    packageName: "@sdkwork/mall-pc-order",
    path: "/buyer/logistics",
    screen: "logistics",
    surface: "buyer",
    title: "物流跟踪",
    titleKey: "order.routes.logistics.title",
  },
] as const satisfies readonly SdkworkMallPcRouteContribution[];
