import type { SdkworkMallH5RouteContribution } from "@sdkwork/mall-h5-core";

export const sdkworkMallH5BuyerRoutes = [
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.dashboard",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer",
    screen: "dashboard",
    surface: "buyer",
    title: "我的",
    titleKey: "buyer.routes.dashboard.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.addresses",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/addresses",
    screen: "addresses",
    surface: "buyer",
    title: "地址管理",
    titleKey: "buyer.routes.addresses.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.coupons",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/coupons",
    screen: "coupons",
    surface: "buyer",
    title: "领券中心",
    titleKey: "buyer.routes.coupons.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.after-sales",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/after-sales",
    screen: "after-sales",
    surface: "buyer",
    title: "售后",
    titleKey: "buyer.routes.after-sales.title",
  },
] as const satisfies readonly SdkworkMallH5RouteContribution[];
