import type { SdkworkMallH5RouteContribution } from "@sdkwork/mall-h5-core";

export const sdkworkMallH5BuyerRoutes = [
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.dashboard",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer",
    screen: "dashboard",
    surface: "buyer",
    title: "我的",
    titleKey: "buyer.routes.dashboard.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.addresses",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/addresses",
    screen: "addresses",
    surface: "buyer",
    title: "地址管理",
    titleKey: "buyer.routes.addresses.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.coupons",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/coupons",
    screen: "coupons",
    surface: "buyer",
    title: "领券中心",
    titleKey: "buyer.routes.coupons.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.after-sales",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/after-sales",
    screen: "after-sales",
    surface: "buyer",
    title: "售后",
    titleKey: "buyer.routes.after-sales.title",
  },
  {
    auth: "required",
    capability: "after-sales",
    domain: "commerce",
    id: "buyer.mall.aftersales.select-order",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/after-sales/select-order",
    screen: "select-order",
    surface: "buyer",
    title: "选择订单",
    titleKey: "buyer.routes.select-order.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.invoices",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/invoices",
    screen: "invoices",
    surface: "buyer",
    title: "发票",
    titleKey: "buyer.routes.invoices.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.favorites",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/favorites",
    screen: "favorites",
    surface: "buyer",
    title: "我的收藏",
    titleKey: "buyer.routes.favorites.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.footprint",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/footprint",
    screen: "footprint",
    surface: "buyer",
    title: "浏览足迹",
    titleKey: "buyer.routes.footprint.title",
  },
  {
    auth: "required",
    capability: "buyer",
    domain: "commerce",
    id: "buyer.mall.messages",
    packageName: "@sdkwork/mall-h5-buyer",
    path: "/buyer/messages",
    screen: "messages",
    surface: "buyer",
    title: "消息中心",
    titleKey: "buyer.routes.messages.title",
  },
] as const satisfies readonly SdkworkMallH5RouteContribution[];
