import type { SdkworkMallH5RouteContribution } from "@sdkwork/mall-h5-core";

export const sdkworkMallH5CatalogRoutes = [
  {
    auth: "public",
    capability: "catalog",
    domain: "commerce",
    id: "storefront.mall.categories",
    packageName: "@sdkwork/mall-h5-catalog",
    path: "/categories",
    screen: "categories",
    surface: "storefront",
    title: "分类",
    titleKey: "catalog.routes.categories.title",
  },
  {
    auth: "public",
    capability: "catalog",
    domain: "commerce",
    id: "storefront.mall.category-detail",
    packageName: "@sdkwork/mall-h5-catalog",
    path: "/categories/:categoryId",
    screen: "categories",
    surface: "storefront",
    title: "类目商品",
    titleKey: "catalog.routes.category-detail.title",
  },
  {
    auth: "public",
    capability: "catalog",
    domain: "commerce",
    id: "storefront.mall.search",
    packageName: "@sdkwork/mall-h5-catalog",
    path: "/search",
    screen: "search",
    surface: "storefront",
    title: "搜索",
    titleKey: "catalog.routes.search.title",
  },
  {
    auth: "public",
    capability: "catalog",
    domain: "commerce",
    id: "storefront.mall.product-detail",
    packageName: "@sdkwork/mall-h5-catalog",
    path: "/product/:productId",
    screen: "product-detail",
    surface: "storefront",
    title: "商品详情",
    titleKey: "catalog.routes.product-detail.title",
  },
] as const satisfies readonly SdkworkMallH5RouteContribution[];
